"use client";
import { useState } from "react";
import { useWorkspace } from "./Workspace";
import { api, compounds, fmt } from "./types";
import { Title } from "./Views";
type Option = { compound: string; pit_before_lap: number; total_remaining_s: number; gain_vs_stay_s: number };
type Result = { stay_out_total_s: number; scenario_choice: Partial<Option> & { action?: string }; options: Option[]; limitations: string[] };
export function Strategy({ demo = false }: { demo?: boolean }) {
  const { selection, report } = useWorkspace();
  const [values, setValues] = useState({ current_lap: String(selection?.lap || 1), remaining_laps: "20", current_pace_s: String(report?.source_row.lap_time || 85), current_degradation_s_per_lap: "0", pit_loss_s: "22" });
  const [candidates, setCandidates] = useState(compounds.map(compound => ({ compound, enabled: compound === "MEDIUM", fresh_pace_s: "83", degradation_s_per_lap: "0.08" })));
  const [result, setResult] = useState<Result | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  function preset(kind: string) {
    setValues({ current_lap: "20", remaining_laps: "20", current_pace_s: "85", current_degradation_s_per_lap: "0.15", pit_loss_s: kind === "neutralized" ? "10" : "22" });
    setCandidates(compounds.map(compound => ({ compound, enabled: compound === "MEDIUM", fresh_pace_s: kind === "slow" ? "86" : "83", degradation_s_per_lap: "0.08" }))); setResult(null);
  }
  return <><Title title={demo ? "Demo scenarios" : "Pit strategy scenarios"} text="Compare staying out with a single stop at each possible remaining lap. Every pace, slope and pit loss below is an explicit scenario input." />
    <p className="notice">Illustrative defaults, not a race recommendation. No weather crossover, rejoin traffic, tyre allocation or race-rule checks. Remaining laps and pit loss are your assumptions; they are not inferred from a practice session.</p>
    {demo && <div className="button-row"><button onClick={() => preset("normal")}>Fresh-tyre advantage</button><button onClick={() => preset("neutralized")}>Lower pit-loss scenario</button><button onClick={() => preset("slow")}>Slow replacement tyre</button></div>}
    <form className="card" onSubmit={async e => { e.preventDefault(); setBusy(true); setError(""); setResult(null); try { setResult(await api<Result>("strategy", { ...Object.fromEntries(Object.entries(values).map(([k, v]) => [k, Number(v)])), candidates: candidates.filter(c => c.enabled).map(c => ({ compound: c.compound, fresh_pace_s: Number(c.fresh_pace_s), degradation_s_per_lap: Number(c.degradation_s_per_lap) })) })); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}>
      <fieldset disabled={busy}><div className="controls">{Object.entries(values).map(([k, v]) => <label key={k}>{({ current_lap: "Last completed lap", remaining_laps: "Remaining laps", current_pace_s: "Next lap pace · s", current_degradation_s_per_lap: "Current slope · s/lap", pit_loss_s: "Pit time loss · s" } as Record<string, string>)[k]}<input required type="number" step={k.endsWith("laps") || k === "current_lap" ? "1" : "any"} value={v} onChange={e => { setValues({ ...values, [k]: e.target.value }); setResult(null); }} /></label>)}</div>
        <p className="muted">The next-lap pace is initially seeded from the selected observed lap where available. It is an editable assumption, not a forecast. Positive slope means slowing each lap.</p>
        <div className="table"><table><thead><tr><th>Use</th><th>Replacement compound</th><th>First lap pace · s</th><th>Slope · s/lap</th></tr></thead><tbody>{candidates.map((c, i) => <tr key={c.compound}><td><input aria-label={`Use ${c.compound}`} type="checkbox" checked={c.enabled} onChange={e => { setCandidates(candidates.map((v, j) => j === i ? { ...v, enabled: e.target.checked } : v)); setResult(null); }} /></td><td><span className={`tag ${c.compound}`}>{c.compound}</span></td>{(["fresh_pace_s", "degradation_s_per_lap"] as const).map(key => <td key={key}><input aria-label={`${c.compound} ${key}`} required={c.enabled} disabled={!c.enabled} type="number" step="any" value={c[key]} onChange={e => { setCandidates(candidates.map((v, j) => j === i ? { ...v, [key]: e.target.value } : v)); setResult(null); }} /></td>)}</tr>)}</tbody></table></div><div className="button-row"><button className="primary" disabled={!candidates.some(c => c.enabled)}>{busy ? "Comparing…" : "Compare pit scenarios"}</button></div></fieldset>
    </form>{error && <p role="alert" className="error">{error}</p>}{result && <section className="card"><h2>Best outcome under these assumptions</h2><p>{result.scenario_choice.action === "STAY_OUT" ? "Stay out" : `Pit before lap ${result.scenario_choice.pit_before_lap} for ${result.scenario_choice.compound}`}</p><p className="muted">Stay-out total: {fmt(result.stay_out_total_s)} s. Pit occurs before the specified lap; that lap uses the replacement-tyre pace.</p><div className="table"><table><thead><tr><th>Compound</th><th>Pit before lap</th><th>Remaining time / s</th><th>Gain vs stay / s</th></tr></thead><tbody>{result.options.slice(0, 10).map(o => <tr key={`${o.compound}-${o.pit_before_lap}`}><td>{o.compound}</td><td>{o.pit_before_lap}</td><td>{fmt(o.total_remaining_s)}</td><td>{fmt(o.gain_vs_stay_s)}</td></tr>)}</tbody></table></div><p className="muted">Best ten of {result.options.length} one-stop options. Negative gain means slower than staying out.</p>{result.limitations.map(l => <p className="muted" key={l}>{l}</p>)}</section>}</>;
}
